### PR TITLE
Add a web mapper

### PR DESCRIPTION
**Pull request by robbkidd**
Renders update every hour at 11 minutes past. When first bringing a server
up, no map is served until the cron job runs for the first time.

### CODE REVIEW

**Comment by jjasghar** [comment]
Awesome, I'll verify this ASAP. Thanks! :metal:

**Comment by robbkidd** [comment]
Mebbe the command in the cron could be a shell script that cron calls so that a human could choose to run it easily ad-hoc. Rendering maps takes a minute (or longer once the world gets bigger), so I'm not sure we want it in the Chef run itself.

**Comment by robbkidd** [comment]
But once run:
maaaaaap

**Comment by jjasghar** [comment]
OOOHHH pretty.

**Pull request merged**
